### ISSUE TITLE
running "hazel ." returns a permission denied error

### ISSUE THREAD

**Issue by rmrgh** [c7/hazel#6]
full stacktrace

```
➜  test-hazel hazel .
      create  /config/initializers
/home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /config (Errno::EACCES)
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `each'
        from /home/vagrant/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:50:in `block in invoke!'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:49:in `invoke!'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:14:in `empty_directory'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/hazel-0.0.8/lib/hazel/cli.rb:36:in `block in create_empty_directories'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/hazel-0.0.8/lib/hazel/cli.rb:35:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/hazel-0.0.8/lib/hazel/cli.rb:35:in `create_empty_directories'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/gems/hazel-0.0.8/bin/hazel:6:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/hazel:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/hazel:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by peterhellberg** [comment]
Yes, this should not be allowed (Hazel should output a nicer error if unable to write files, it should also check that you don't provide an empty name)
